### ISSUE TITLE
"Sending bug report in WSV3"

### ISSUE THREAD

**Issue by parkedcar873** [relative/turboactivate-emulator#2]
What's up with the "Sending bug report" popup that seems to want to clutter and freeze the application?

**Comment by parkedcar873** [comment]
@relative

**Comment by relative** [comment]
Can i see a screenshot of the error? If i'm right it's from wsv3

**Comment by parkedcar873** [comment]
@relative It happens whenever I play a radar loop in WSV3. I saw it last night and this morning, and of course once I submit this report, it doesn't show up. If it happens again, I'll get a screenshot and send it over.

**Comment by relative** [comment]
I can take a look later but it was most likely just a bug in WSV3, if you get it again please take a screenshot with win+shift+s or PrtScr and paste it here

**Comment by parkedcar873** [comment]
![jhghgghgh (2)](https://user-images.githubusercontent.com/90718512/133323907-ef25e634-b9bc-4331-bd19-371ff0dc7694.PNG)
I got it! @relative

**Comment by relative** [comment]
Did it show a dialog with 4 buttons with icons and a large box in the middle after?

**Comment by parkedcar873** [comment]
@relative Nope. All it does it show those pop-ups, they sit for about 15 seconds and then go away. Sometimes there's only one or two but in some cases there can be several and they just continue and they freeze the application so hard I have to go into task manager just to end WSV3.

**Comment by relative** [comment]
I redownloaded WSV3 and am not seeing the issue. is it possible for you to make a screen recording of the issue when it happens (from starting WSV3 to the error dialog)?

**Comment by parkedcar873** [comment]
@relative likely won't be able to catch it. It only occurs maybe about 30% of the time I use WSV3 and restarting it usually fixes the issue. I'm now concerned if there is a way to make it so that it doesn't show those popups.

**Comment by relative** [comment]
go to WSV3 in the top left, Advanced > Show exceptions and click it so it shows a checkmark

then once it shows up again it should show more detailed information about the crash, then you can take another screenshot again
